export const BOOKING_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
});

export const BOOKING_STATUS_FILTERS = ['ALL', ...Object.values(BOOKING_STATUS)];
