export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/",
  RESOURCES: "/resources",
  RESOURCE_DETAIL: "/resources/:resourceId",
  BOOK_RESOURCE: "/bookings/new",
  MY_BOOKINGS: "/bookings/my",
  CREATE_TICKET: "/tickets/new",
  MY_TICKETS: "/tickets/my",
  TICKET_DETAIL: "/tickets/:ticketId",
  ADMIN_BOOKING_APPROVALS: "/admin/bookings",
  USER_ROLE_MANAGEMENT: "/admin/users/roles",
  TECHNICIAN_QUEUE: "/technician/queue",
  UNAUTHORIZED: "/unauthorized",
};
